spring.application.name=fynova-backend
server.port=8081

# PostgreSQL Verbindung. Die Werte für DB_USER und DB_PASS müssen in der Umgebungsvariablen bzw. in .env gesetzt werden. 
#Statt der echten Werte werden die Platzhalter ${DB_USER} und ${DB_PASS} als dummydata verwendet.
#Oder kannst direkt den Ordner zu .gitignore hinzufügen, damit die Datei nicht getrackt wird.
# jdbc:postgresql dien als Protokoll für die Verbindung zu PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} 
spring.datasource.username=${DB_USER}  
spring.datasource.password=${DB_PASS}

# Hibernate Einstellungn    
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

